version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2705Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: DADA_ExtendedProperty
  gitServerName: rimaSCName
  gitUrl: https://github.com/ParmelaDohling579
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_2705.integrations:AlertsCRTandERT
  packages:
  - name: SIQA_GIT_2705Project
    version: "1.0"
  - name: DADA_ExtendedProperty
    version: "1.0"
- serviceName: pub.alert:emit
  packages:
  - name: WmPublic
    version: 12.1.0.0.863
- serviceName: project.siqa_git_2705.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_2705Project
    version: "1.0"
  - name: DADA_ExtendedProperty
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 12.1.0.0.863
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 12.1.0.0.863
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 12.1.0.0.863
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
